### Recuperar todos los TODOs
GET http://localhost:3030/todos

### Crear un TODO
POST http://localhost:3030/todos
Content-Type: application/json

{
  "title": "otro todo",
  "completed": false
}

### Actualizar un TODO
PUT http://localhost:3030/todos/7bd56810-31b1-486f-8c3d-4a4120bd8a62
Content-Type: application/json

{
  "title": "Todo editado"
}

### Eliminar un TODO
DELETE http://localhost:3030/todos/7bd56810-31b1-486f-8c3d-4a4120bd8a62
