### Recuperar todos los TODOs
GET http://localhost:3030/todos/c6f1c9f1-4f3a-4d3e-8f9e-6a2d4a1a8e5d

### Crear un TODO
POST http://localhost:3030/todos/c6f1c9f1-4f3a-4d3e-8f9e-6a2d4a1a8e5d
Content-Type: application/json

{
  "title": "otro todo"
}

### Actualizar un TODO
PUT http://localhost:3030/todos/c6f1c9f1-4f3a-4d3e-8f9e-6a2d4a1a8e5d/f7a846d3-4b8a-4a1d-946b-df76ec6bd90f
Content-Type: application/json

{
  "title": "todo editado"
}

### Eliminar un TODO
DELETE http://localhost:3030/todos/c6f1c9f1-4f3a-4d3e-8f9e-6a2d4a1a8e5d/c6f1c9f1-4f3a-4d3e-8f9e-6a2d4a0a8e5d

### Actualizar el orden de los TODOs
PUT http://localhost:3030/todos/c6f1c9f1-4f3a-4d3e-8f9e-6a2d4a1a8e5d
Content-Type: application/json

[
  {
    "id": "f7a846d3-4b8a-4a1d-946b-df76ec6bd90f",
    "title": "todo editado",
    "completed": false,
    "order": 0,
    "user": "c6f1c9f1-4f3a-4d3e-8f9e-6a2d4a1a8e5d"
  },
  {
    "id": "ede44c6a-13b1-49fa-8dbe-b7cc873b0390",
    "title": "otro todo",
    "completed": false,
    "order": 1,
    "user": "c6f1c9f1-4f3a-4d3e-8f9e-6a2d4a1a8e5d"
  }
]

### Crear un usuario
POST http://localhost:3030/users
