export const TODO_ACTIONS = {
  UPDATE_LIST: 'UPDATE_LIST',
  ADD: 'ADD_TODO',
  REMOVE: 'REMOVE_TODO',
  CHECK: 'CHECK_TODO',
  EDIT_TITLE: 'EDIT_TITLE',
  CLEAR_COMPLETED: 'CLEAR_COMPLETED',
  FILTER_CHANGE: 'FILTER_CHANGE',
} as const
