export const TODO_ACTIONS = {
  INIT_TODOS: 'INIT_TODOS',
  ADD: 'ADD',
  COMPLETE: 'COMPLETE',
  REMOVE: 'REMOVE',
  UPDATE: 'UPDATE',
  FILTER_CHANGE: 'FILTER_CHANGE',
  CLEAR_COMPLETED: 'CLEAR_COMPLETED',
} as const
